### ISSUE TITLE
Don't token generate

### ISSUE THREAD

**Issue by djara844** [PouleR/apple-music-api#16]
Hi

When generating the token with the following code, it generates the error at the end...

`<?php

require 'vendor/autoload.php';

$tokenGenerator = new PouleR\AppleMusicAPI\AppleMusicAPITokenGenerator();
$jwtToken = $tokenGenerator->generateDeveloperToken(
    'Y7URPTMPVR',
    'Q98J8XZYYC',
    './AuthKey_Q98J8XZYYC.p8',
);

$curl = new \Symfony\Component\HttpClient\CurlHttpClient();
$client = new PouleR\AppleMusicAPI\APIClient($curl);
$client->setDeveloperToken($jwtToken);

$api = new PouleR\AppleMusicAPI\AppleMusicAPI($client);

$result = $api->getCatalogPlaylist('nl', 'pl.a56541661a7a4cca95ddeca24e5e5316');

print_r($result);`

Error

PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PouleR\AppleMusicAPI\APIClient::setDeveloperToken() must be of the type string, null given, called in /home/diego/Escritorio/generator/index.php on line 14 and defined in /home/diego/Escritorio/generator/vendor/pouler/apple-music-api/src/APIClient.php:61
Stack trace:
#0 /home/diego/Escritorio/generator/index.php(14): PouleR\AppleMusicAPI\APIClient->setDeveloperToken()
#1 {main}
  thrown in /home/diego/Escritorio/generator/vendor/pouler/apple-music-api/src/APIClient.php on line 61

**Comment by PouleR** [comment]
The method generateDeveloperToken returns a null value in this case, are you sure the AuthKey file exists at that location? Or you can add some logging to the try..catch block to see what's the reason for the internal exception
