### ISSUE TITLE
503 Error from some servers (ie. Cloudflare)

### ISSUE THREAD

**Issue by shawns582** [PouleR/apple-music-api#7]
First of thanks a lot for this wrapper- huge help.

For some reason I am getting a 503 error response from the Apple Music API when I make the request from servers that are using Cloudflare. Any idea why this might be? Not sure if adding any type of header would help fix it? I'd appreciate any thoughts. I've been stuck on this for a few months. 

The same request with this wrapper works fine on other servers.

**Comment by PouleR** [comment]
Hi @shawns582,

Can you maybe add a trace for this? Did you try to use a different user-agent in the request?
Or for e.g. what happens when you execute the same request with cURL ?

**Comment by shawns582** [comment]
@PouleR  thanks for the reply. Here is a trace:
`2020/03/02 13:41:24 [error] 28844#28844: *3040 FastCGI sent in stderr: "PHP mess
age: PHP Fatal error:  Uncaught PouleR\AppleMusicAPI\AppleMusicAPIException: API
 Request: catalog/us/search?term=magic&types=songs&limit=10, Service Unavailable
 (503) in /var/www/soulsence.me/vendor/pouler/apple-music-api/src/APIClient.php:
124
Stack trace:
#0 /var/www/soulsence.me/public/api/common/getTopArtistSongsApple.php(25): Poule
R\AppleMusicAPI\APIClient->apiRequest('GET', 'catalog/us/sear...')
#1 /var/www/soulsence.me/public/api/v1.3/testAppleMusicApi.php(44): TOP\AppleMus
ic\AppleMusic->searchCatalog('us', 'magic', 'songs')
#2 {main}
  thrown in /var/www/soulsence.me/vendor/pouler/apple-music-api/src/APIClient.ph
p on line 124" while reading response header from upstream, client: 50.113.90.13
4, server: soulsence.me, request: "GET /api/v1.3/testAppleMusicApi.php HTTP/1.1"
, upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock:", host: "soulsence.me"`

I tried using an authenticated curl request and seem to get a "Service Unavailable" error message. I tried setting CURLOPT_USERAGENT and CURLOPT_REFERER in the php file, but still no luck. That code looks like this:

`//CURL
$url = 'https://api.music.apple.com/v1/catalog/us/search?term=caldonia&types=songs';

// Initialize cURL
$curl = curl_init();

// Set the options
curl_setopt($curl,CURLOPT_URL, $url);
curl_setopt($curl,CURLOPT_USERAGENT,'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.13) Gecko/20080311 Firefox/2.0.0.13');
curl_setopt($curl, CURLOPT_REFERER, 'https://soulsence.me/');
curl_setopt($curl, CURLOPT_HTTPHEADER,
	array(
		"Accept: */*",
		"Content-Type: application/json",
        'Authorization: Bearer ' .$access_token
    ));

curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

//execute the post
$curlResult = curl_exec($curl);
$searchResult = json_decode($curlResult, true);`

**Comment by PouleR** [comment]
Thank you for the trace. If even with you cURL code the response is 503 it doesn't seem to make a difference if you use another user agent. Did you already contact CloudFare or Apple about this? 

Maybe you're hitting a rate limit?

**Comment by shawns582** [comment]
Yeah I've contacted both but unfortunately no response. I was able to get
the curl code to work on our production server which uses a paid version of
Cloudflare, but not on another server that uses a free version of it.

Likely a Cloudflare issue, just came here in desperation wondering if there
were any params or headers that could be passed to get around this.
