### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by aldrichdev** [PouleR/apple-music-api#9]
I have the following code (almost identical to the code in the readme):

```
<?php 
require 'vendor/autoload.php';

$authKeyFilePath = __DIR__ . '/data/AuthKey_redacted.p8';
$tokenGenerator = new PouleR\AppleMusicAPI\AppleMusicAPITokenGenerator();
$jwtToken = $tokenGenerator->generateDeveloperToken(
    'redacted team id',
    'redacted key id',
    $authKeyFilePath
);

$curl = new \Symfony\Component\HttpClient\CurlHttpClient();
$client = new PouleR\AppleMusicAPI\APIClient($curl);
$client->setDeveloperToken($jwtToken);

$api = new PouleR\AppleMusicAPI\AppleMusicAPI($client);

$result = $api->getCatalogPlaylist('nl', 'pl.a56541661a7a4cca95ddeca24e5e5316');

print_r($result);

?>
```

I am calling this PHP file via the command line like `php testit.php`. It errors with:
```
PHP Fatal error:  Uncaught PouleR\AppleMusicAPI\AppleMusicAPIException: API Request: catalog/nl/playlists/pl.a56541661a7a4cca95ddeca24e5e5316, SSL peer certificate or SSH remote key was not OK for "https://api.music.apple.com/v1/catalog/nl/playlists/pl.a56541661a7a4cca95ddeca24e5e5316". (0) in C:\Dev\red\reda\vendor\pouler\apple-music-api\src\APIClient.php:109
Stack trace:
#0 C:\Dev\red\reda\vendor\pouler\apple-music-api\src\AppleMusicAPI.php(136): PouleR\AppleMusicAPI\APIClient->apiRequest('GET', 'catalog/nl/play...')
#1 C:\Dev\red\reda\testit.php(18): PouleR\AppleMusicAPI\AppleMusicAPI->getCatalogPlaylist('nl', 'pl.a56541661a7a...')
#2 {main}
  thrown in C:\Dev\red\reda\vendor\pouler\apple-music-api\src\APIClient.php on line 109
```

However, if I print my developer token and put it in Postman in a request to https://api.music.apple.com/v1/catalog/nl/playlists/pl.a56541661a7a4cca95ddeca24e5e5316, the response is 200.

**Comment by PouleR** [comment]
Hi @aldrichdev ,

I've just tested the same situation and I don't see any SSL errors. Are you maybe using a proxy that uses a self signed certificate? That's the only reason I can think of why the request would fail.

Or what you can also try is to use it in a native cUrl command, what is the output for that?

**Comment by aldrichdev** [comment]
@PouleR, sorry - I didn't mean to post this actually (it was a mistake), since I just needed the developer token, which the script was successful at providing.

I am still able to reproduce this issue, so I will help you troubleshoot. I am not using a proxy (that I know of). By native cUrl command, do you mean through the terminal or through PHP code?
